### ISSUE TITLE
Errors. PLS HELP

### ISSUE THREAD

**Issue by SplinterProject** [EDDYMENS/awe-blacklabel-sdk#6]
The script files are untouched. Only the credentials are modified

1) Awe\Blacklabel\test::testGetPerformers
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:44
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:51

2) Awe\Blacklabel\test::testGetMorePerformers
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:44
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:60

3) Awe\Blacklabel\test::testGetPerformerAlbum
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:81
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:74

4) Awe\Blacklabel\test::testGetPerformerDetailsByName
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:68
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:83

5) Awe\Blacklabel\test::testGetAlbumItem
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:107
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:92

6) Awe\Blacklabel\test::testGeneralSearch
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:120
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:101

7) Awe\Blacklabel\test::testGetFilterList
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:143
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:110

8) Awe\Blacklabel\test::testGetLanguages
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:200
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:119

9) Awe\Blacklabel\test::testGetPerformerRecommendations
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:169
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:128

10) Awe\Blacklabel\test::testAuthenticateUser
Undefined offset: 1

G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:281
G:\1X\htdocs\awe-blacklabel-sdk-master\src\SDK.php:181
G:\1X\htdocs\awe-blacklabel-sdk-master\tests\test.php:137

ERRORS!
Tests: 10, Assertions: 0, Errors: 10.

**Comment by EDDYMENS** [comment]
@SplinterProject I assume you resolved it :)

**Comment by SplinterProject** [comment]
Yeah, somehow i did...but i cant manage to find the link to performer details...like photos and albums

**Comment by EDDYMENS** [comment]
Ah ok

**Comment by EDDYMENS** [comment]
I will close this issue then
